config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '//admin', as: 'rails_admin'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :trips do
    get "/random-wheel", to: "pages#random_wheel"
    get "/invite", to: "pages#invite"
    post "/invite", to: "pages#send_invite"
    get "/notifications", to: "pages#notifications"
    get "/board", to: "trips#board"
    resources :user_trips, only: [:create, :destroy]
    resources :activities, only: [:index, :new, :create] do
      resources :participations, only: [:create, :destroy]
    end

    resources :activities, only: [:show, :destroy, :edit, :update]

    resources :rooms, only: [:index, :show] do
      resources :messages, only: :create
    end
    resources :wallets, only: [:show, :create, :update] do
      resources :bills, only: [:index, :create, :update, :destroy]
    end
  end
end

app/models/trip.rb
class Trip < ApplicationRecord
  validates :destination, presence: true

  has_many :activities, dependent: :destroy
  has_many :user_trips, dependent: :destroy
  has_many :users, through: :user_trips
  has_many :notifications, dependent: :destroy
  has_many :rooms, dependent: :destroy

  def creator
    @users = User.all
    @creator = @users.select do |user|
      self.user_trips.find_by_user_id(user.id) && self.user_trips.find_by_user_id(user.id).creator == true
    end
    return @creator.first
  end

  def creator?(user)
    return true if self.user_trips.find_by_user_id(user.id) && self.user_trips.find_by_user_id(user.id).creator == true
  end

  def participates?(user)
    return true if self.user_trips.find_by_user_id(user.id)
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  def index
    @trips = policy_scope(Trip)
    @trips = UserTrip.where(user_id: current_user.id)
  end

  def show
    authorize @trip
  end

  def new
    @trip = Trip.new
    authorize @trip
  end

  def create
    @trip = Trip.new(trip_params)
    @trip.user_id = current_user.id
    authorize @trip
    if @trip.save!
      user_trip = UserTrip.new(user_id: current_user.id, trip_id: @trip.id, creator: true)
      user_trip.save!
      create_chats
      redirect_to @trip, notice: "Trip created successfully."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @trip
  end

  def update
    authorize @trip
    if @trip.update(trip_params)
      create_notification("updated")
      redirect_to @trip, notice: "Trip updated successfully."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @trip
    @trip.destroy
    redirect_to trips_path, status: :see_other
  end

  def board
    @trip = Trip.find(params[:trip_id])
    @user_trip = @trip.user_trips.find_by_user_id(current_user.id)
    authorize @trip
  end

  private

  def set_trip
    @trip = Trip.find(params[:id])
  end

  def trip_params
    params.require(:trip).permit(:destination, :start_date, :end_date)
  end

  def create_chats
    @room_general = Room.new(trip_id: @trip.id, name: "General")
    @room_activities = Room.new(trip_id: @trip.id, name: "Activities")
    @room_housing = Room.new(trip_id: @trip.id, name: "Housing")
    @room_general.save!
    @room_activities.save!
    @room_housing.save!
  end

  def create_notification(action)
    @user = current_user
    @trip = Trip.find(params[:id])
    @notification = Notification.new(content: "#{@trip.destination} trip was #{action}")
    @notification.user_id = current_user.id
    @notification.trip_id = @trip.id
    @notification.save!
    @notification.generate_user_notifications
  end
end

app/views/trips/_form.html.erb
<% if @trip.id.nil? %>
  <h1 class="text-center fs-2 py-2">Create my trip</h1>
<% else %>
  <h1 class="text-center fs-2 py-2">Update my trip</h1>
<% end %>
      <%= simple_form_for @trip do |f| %>
        <%= f.input :destination %>
        <%= f.input :start_date, as: :string, required: false, html5: true, as: :date %>
        <%= f.input :end_date, as: :string, required: false, html5: true, as: :date %>
        <div class="centered-box mt-4">
          <%= f.submit class:"btn btn-blue-full" %>
      <% end %>
          <% if @trip.user_trips.find_by_user_id(current_user.id) %>
            <%= button_to "Quit trip", trip_user_trip_path(@trip, @trip.user_trips.find_by_user_id(current_user.id)), method: :delete, class:"btn btn-danger ms-1" %>
          <% end %>
          <%= link_to 'Back', trips_path, class:"btn btn-white ms-1" %>
        </div>
        <!--
          <% if  @trip.user_id == current_user.id %>
            <%= link_to "Destroy Trip", trip_path(@trip), class:"btn btn-danger", data: { turbo_method: :delete, turbo_confirm: 'Are you sure ?'} %>
          <% end %>
        -->

app/views/trips/board.html.erb
<div class="container responsive min-h-100 pt-4 p-large">
  <div class="nav nav-tabs tabs-trip mx-2 mb-2 rounded-4 p-0 row justify-content-between" id="myTab" role="tablist">

    <div class="col-4 nav-item" role="presentation">
      <button class="nav-link active" id="trip-users-tab" data-bs-toggle="tab" data-bs-target="#trip-users-tab-pane" type="button" role="tab" aria-controls="trip-users-tab-pane" aria-selected="true"><i class="fa-solid fa-users"></i></button>
    </div>

    <div class="col-4 nav-item" role="presentation">
      <button class="nav-link" id="manage-tab" data-bs-toggle="tab" data-bs-target="#manage-tab-pane" type="button" role="tab" aria-controls="manage-tab-pane" aria-selected="false"><i class="fa-solid fa-gears"></i></button>
    </div>

    <div class="col-4 nav-item" role="presentation">
      <button class="nav-link" id="invite-tab" data-bs-toggle="tab" data-bs-target="#invite-tab-pane" type="button" role="tab" aria-controls="invite-tab-pane" aria-selected="false">
        <i class="fa-solid fa-user-plus"></i>
      </button>
    </div>
  </div>

  <div class="tab-content px-2" id="myTabContent">

    <div class="tab-pane fade show active" id="trip-users-tab-pane" role="tabpanel" aria-labelledby="trip-users-tab" tabindex="0">
    <h1 class="text-center fs-2 py-2">Amigos of my trip</h1>
      <% @trip.users.each do |user| %>
        <% if user != current_user %>
          <div class="container p-2 my-3 shadow rounded-4 bg-white">
            <div class="row p-1 d-flex align-items-start">
              <div class="col-4 col-md-2">
                <%= cl_image_tag user.photo.key, height:100, class:"rounded-4 obj-fit" %>
              </div>
              <div class="col-8 col-md-10 ps-3">
                <p class="m-0 fw-bold"><%= user.first_name %> <%= user.last_name %></p>
                <p class="m-0 fs-7"><%= user.email %></p>
                <p class="m-0 fs-7"><%= pluralize(Participation.where(user_id: user.id).count, "activity") %> in common</p>
                
                <p class="m-0 fs-7">
                  <% if current_user.wallet.account(user) < 0 %>
                    😱 You owe this amigo
                  <% elsif current_user.wallet.account(user) == 0 %>
                    🤓 All Accounts Balanced
                  <% else %>
                    😎 This amigo owes you
                  <% end %>
                </p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="tab-pane fade" id="manage-tab-pane" role="tabpanel" aria-labelledby="manage-tab" tabindex="0">
      <%= render 'form', trip: @trip %>
    </div>

    <div class="tab-pane fade" id="invite-tab-pane" role="tabpanel" aria-labelledby="invite-tab" tabindex="0">
      <%= render "pages/invite", trip: @trip%>
    </div>
  </div>
</div>

app/views/trips/edit.html.erb
<div class="mb-5">
  <div class="row justify-content-center">
    <div class="col-sm-6 grey-bg p-5 rounded-4">
      <div class="text-center">
        <h1 class="text-center fs-2 py-2">Update my trip</h1>
        <hr>
      </div>

      <%= render "form", trip: @tri %>
    </div>
  </div>
</div>

app/views/trips/index.html.erb
<div class="bg-gradient-img text-light px-3 h-100 min-h-100">
  <div class="container responsive pt-3 p-large">
    <div class="row align-items-center justify-content-between pb-3 border-bottom border-light">
      <div class="col p-0">
        <%= link_to root_path do %>
          <img src="https://res.cloudinary.com/laura-latuillerie/image/upload/v1662627064/amigo-logo_iagptt.svg" id="logo">
        <% end %>
      </div>
      <div class="col p-0 text-end">
        <%= link_to "Create a trip", new_trip_path, class:"btn btn-white" %>
      </div>
    </div>
    <div class="row">
      <h1 class="text-center fs-2 mt-3">All my trips</h1>
      <% @trips.each do |user_trip|%>
        <div class="col-12 mt-2 mb-4 p-4 bg-light text-center border-sm">
          <h2 class="fs-3"><strong><%= link_to user_trip.trip.destination, trip_path(user_trip.trip), class:"text-decoration-none" %></strong></h2>
          <p class="p-0 mb-2 text-dark">
            <i class="fa-solid fa-calendar-days text-dark-blue"></i> <%= user_trip.trip.start_date.strftime("%d %b") %> - <%= user_trip.trip.end_date.strftime("%d %b %Y") %>
          </p>
          <div class="d-flex justify-content-center">
            <h5 class="me-2"><span class="badge rounded-pill bg-dark-blue text-light"><%= user_trip.trip.users.count %> Amigos</span></h5>
            <h5><span class="badge rounded-pill bg-dark-blue text-light"><%= user_trip.trip.activities.count %> Activities</span></h5>
          </div>
          <hr class="text-dark">
          <%= link_to "Manage my trip", trip_path(user_trip.trip) %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/trips/new.html.erb
<div class="container my-5 responsive px-4">
  <div class="row centered-box">
    <div class="col">
      <%= render "form", trip: @trip %>
    </div>
  </div>
</div>

app/views/trips/show.html.erb
<div class="h-100 px-3 pt-4">
  <div class="container responsive rounded-4 trip-card">
    <div class="row justify-content-between align-items-end">
      <div class="col p-0">
        <%= link_to trips_path do %>
          <img src="https://res.cloudinary.com/laura-latuillerie/image/upload/v1662627064/amigo-logo_iagptt.svg" id="logo">
        <% end  %>
      </div>
      <div class="col p-0 text-end">
        <h6 class="m-0 text-white">Hello, <%= current_user.first_name%> !</h6>
      </div>
    </div>
    <div class="row mt-3 px-2 pt-2 pb-4 rounded-4 bg-light-transparent">
      <div class="col-4">
        <div class="centered-box flex-column rounded-4" data-controller="weather">
          <img src="" alt="Weather Icon" data-weather-target="img" height=70 class="">
          <p class="fs-4 fw-bold" data-weather-target="temp"></p>
        </div>
      </div>
      <div class="col-8 d-flex justify-content-center flex-column rounded-4 p-2">
        <h3><strong><%= @trip.destination %></strong></h3>
        <h6 class="mb-2"><%= @trip.start_date.strftime("%d %b") %> - <%= @trip.end_date.strftime("%d %b %Y") %>
        </h6>
        <div class="d-flex">
          <h5 class="d-block rounded-4 px-3 py-1 border-blue me-1 fw-normal"><i class="fa-solid fa-users text-blue"></i> <%= @trip.users.count %></h5>
          <h5 class="d-block rounded-4 px-3 py-1 border-blue fw-normal"><i class="fa-solid fa-hiking  text-blue"></i> <%= @trip.activities.count %></h5>
        </div>
      </div>
    </div>
    <div class="row justify-content-center trip-card-avatars">
      <div class="col p-0">
        <ul class="text-center">
          <% @trip.users.each do |user| %>
            <li><%= cl_image_tag user.photo.key, class:"avatar-sm" %></li>
          <% end %>
          <li class="bg-white">
            <%= link_to trip_invite_path(@trip) do %>
              <%= image_tag 'icons/plus-icon.png', class:"invite-friend" %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <% if @trip.participates?(current_user) %>
    <div class="container trip-buttons-box">
      <div class="row centered-box text-center">
        <div class="col-6 d-flex justify-content-end mb-2">
          <div class="main-btn d-flex justify-content-center align-items-center rounded-4 my-2">
            <%= link_to trip_activities_path(@trip) do %>
            <!--
            <div class="opacity-80">
              <%= image_tag 'icons/banana-boat.png', height:50 %>
            </div>
            -->
            <h2 class="fs-1">
              <i class="fa-solid fa-person-hiking"></i>
            </h2>
            <p class="mt-2 mb-0 ">Activities</p>
            <% end %>
          </div>
        </div>
        <div class="col-6 d-flex justify-content-start mb-2 ">
          <div class="main-btn centered-box rounded-4 my-2">
            <%= link_to trip_random_wheel_path(@trip), data: {turbo: false} do %>
              <i class="fa-solid fa-dice"></i>
              <!--
              <%= image_tag 'icons/fortune-wheel.png', height:50 %>
              -->
              <p class="mt-2 mb-0 ">AmigoFortune</p>

            <% end %>
          </div>
        </div>
        <div class="col-6  d-flex justify-content-end mt-2 mb-2 ">
          <div class="main-btn centered-box rounded-4">
            <%= link_to trip_board_path(@trip) do %>
              <!--
              <%= image_tag 'icons/passeport.png', height:50%>
              -->
              <i class="fa-solid fa-passport"></i>
              <p class="mt-2 mb-0 ">My Trip</p>
            <% end %>
          </div>
        </div>
        <div class="col-6 d-flex justify-content-start mt-2  mb-2 ">
          <div class="main-btn centered-box rounded-4">
            <%= link_to trip_wallet_path(@trip, UserTrip.find_by_user_id(current_user.id).wallet) do %>
              <!--
              <%= image_tag 'icons/piggy-bank.png', height:50 %>
              -->
              <i class="fa-solid fa-piggy-bank"></i>
              <p class="mt-2 mb-0 ">AmigoBank</p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% else %>
    <div class="centered-box flex-column text-center mt-5">
    <h2>Hello, <%= current_user.first_name%> !</h2>
      <p class="fw-normal">You were invited to join this trip<br>
      <strong>Join your amigos ! 😎</strong></p>
      <%= button_to "Participate", trip_user_trips_path(user_id: current_user.id, trip_id: params[:id]), method: :post, class:"btn btn-blue mt-3"  %>
    </div>
  <% end %>
</div>