config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '//admin', as: 'rails_admin'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :trips do
    get "/random-wheel", to: "pages#random_wheel"
    get "/invite", to: "pages#invite"
    post "/invite", to: "pages#send_invite"
    get "/notifications", to: "pages#notifications"
    get "/board", to: "trips#board"
    resources :user_trips, only: [:create, :destroy]
    resources :activities, only: [:index, :new, :create] do
      resources :participations, only: [:create, :destroy]
    end

    resources :activities, only: [:show, :destroy, :edit, :update]

    resources :rooms, only: [:index, :show] do
      resources :messages, only: :create
    end
    resources :wallets, only: [:show, :create, :update] do
      resources :bills, only: [:index, :create, :update, :destroy]
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand px-3">
  <div class="container-fluid justify-content-center">
      <ul class="navbar-nav w-100 justify-content-between py-0">
        <li class="nav-item d-inline-block">
          <% if !@trip.nil? && !@trip.id.nil? %>
            <%= link_to trip_path(@trip), class: "nav-link" do %>
              <%= image_tag("icons/home-icon.svg", height: '32', width: '32') %>
            <% end %>
            </li>
            <li class="nav-item d-inline-block">
              <%= link_to trips_path, class: "nav-link" do %>
                <%= image_tag("icons/plane-icon.svg", height: '32', width: '32') %>
              <% end %>
            </li>
          <% else %>
            <%= link_to root_path, class: "nav-link" do %>
              <%= image_tag("icons/home-icon.svg", height: '32', width: '32') %>
            <% end %>
          <% end %>
        </li>
        <% if user_signed_in? %>
          <% if !@trip.nil? && !@trip.id.nil? %>
            <li class="nav-item d-inline-block">
              <%= link_to trip_rooms_path(@trip), class:"nav-link" do  %>
                  <%= image_tag("icons/chat-icon.svg", height: '36', width: 'auto') %>
                  <% if UserMessage.display_unread(current_user.id) > 0 %>
                     <span class="position-absolute top-25 start-30 translate-middle badge rounded-pill bg-danger fs-6">
                    <%= UserMessage.display_unread(current_user.id) %>
                    <span class="visually-hidden">unread messages</span>
                    </span>
                  <% end %>
              <% end %>
            </li>

            <li class="nav-item d-inline-block">
              <%= link_to trip_notifications_path(@trip), class:"nav-link position-relative" do  %>
                <%= image_tag("icons/notification-icon.svg", height: '32', width: 'auto') %>
                <% if UserNotification.display_unread(current_user.id) > 0 %>
                  <span class="position-absolute top-25 start-90 translate-middle badge rounded-pill bg-danger fs-6">
                  <%= UserNotification.display_unread(current_user.id) %>
                  <span class="visually-hidden">unread notifications</span>
                  </span>
                <% end %>
              <% end %>
            </li>
          <% end %>

          <li class="nav-item d-inline-block">
            <%= link_to destroy_user_session_path, data: {turbo_method: :delete}, class:"nav-link" do %>
              <%= image_tag("icons/logout-icon.svg", height: '35', width: 'auto') %>
            <% end %>
          </li>
      <% else %>
        <li class="nav-item d-inline-block ">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>