config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '//admin', as: 'rails_admin'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :trips do
    get "/random-wheel", to: "pages#random_wheel"
    get "/invite", to: "pages#invite"
    post "/invite", to: "pages#send_invite"
    get "/notifications", to: "pages#notifications"
    get "/board", to: "trips#board"
    resources :user_trips, only: [:create, :destroy]
    resources :activities, only: [:index, :new, :create] do
      resources :participations, only: [:create, :destroy]
    end

    resources :activities, only: [:show, :destroy, :edit, :update]

    resources :rooms, only: [:index, :show] do
      resources :messages, only: :create
    end
    resources :wallets, only: [:show, :create, :update] do
      resources :bills, only: [:index, :create, :update, :destroy]
    end
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :address, :categories, :description, presence: true
  validates :min_amigos, presence: true, numericality: { only_integer: true }, allow_blank: false

  belongs_to :trip
  has_many :participations, dependent: :destroy
  has_many :users, through: :participations

  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def creator
    @users = User.all
    @creator = @users.select do |user|
      self.participations.find_by_user_id(user.id) && self.participations.find_by_user_id(user.id).creator == true
    end
    return @creator.first
  end

  def creator?(user)
    return true if self.participations.find_by_user_id(user.id) && self.participations.find_by_user_id(user.id).creator == true
  end

  def participates?(user)
    return true if self.participations.find_by_user_id(user.id)
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  before_action :set_trip, only: [:create, :show, :new, :edit, :update, :destroy]
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  def index
    @activities = policy_scope(Activity)
    @activities = Activity.where(trip_id: params[:trip_id])
    @trip = Trip.find(params[:trip_id])
    @activity = Activity.new
    @markers = @activities.geocoded.map do |activity|
      {
      lat: activity.latitude,
      lng: activity.longitude,
      info_window: render_to_string(partial: "info_window", locals: {activity: activity}),
      image_url: helpers.asset_url('tong.svg')
    }
    end
  end

  def show
    authorize @activity
    @markers = [{
      lat: @activity.latitude,
      lng: @activity.longitude,
      info_window: render_to_string(partial: "info_window", locals: {activity: @activity}),
      image_url: helpers.asset_url('tong.svg')
    }]
  end

  def new
    @activity = Activity.new
    authorize @activity
  end

  def create
    @user = current_user
    @activity = Activity.new(activity_params)
    @activity.trip = @trip
    authorize @activity
    if @activity.save!
      participation = Participation.new(user_id: current_user.id, activity_id: @activity.id, creator: true)
      participation.save!
      create_notification(@activity, "created")
      redirect_to trip_activities_path(trip_id: @trip.id), notice: "Activity created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @activity
  end

  def update
    authorize @activity
    if @activity.update(activity_params)
      create_notification(@activity, "updated")
      redirect_to trip_activity_path, notice: "Activity updated successfully."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @activity
    @activity.destroy
    redirect_to trip_activities_path(@trip), status: :see_other
  end

  private

  def activity_params
    params.require(:activity).permit(:categories, :address, :description, :min_amigos, :max_amigos, :title, :date, :photo)
  end

  def set_activity
    @activity = Activity.find(params[:id])
  end

  def set_trip
    @trip = Trip.find(params[:trip_id])
  end

  def create_notification(target, action)
    @user = current_user
    @trip = Trip.find(params[:trip_id])
    @notification = Notification.new(content: "#{target.title} was #{action} by #{@user.first_name}")
    @notification_self = Notification.new(content: "You #{action} #{target.title}")
    @notification.user_id = current_user.id
    @notification.trip_id = @trip.id
    @notification.save!
    @notification_self.user_id = current_user.id
    @notification_self.trip_id = @trip.id
    @notification_self.save!
    generate_user_notifications(@notification, @notification_self, @user)
  end

  def generate_user_notifications(notification, notification_self, current_user)
    @users = @trip.users
    @users.each do |user|
      if user == current_user
        user_notification = UserNotification.new(user_id: user.id, notification_id: notification_self.id, read: false)
      else
        user_notification = UserNotification.new(user_id: user.id, notification_id: notification.id, read: false)
      end
      user_notification.save!
    end
  end
end

app/views/activities/_form.html.erb
<div class="container min-h-100">
  <div class="row">
    <% if @activity.id.nil? %>
      <h1 class="text-center fs-2 py-2">Create activity</h1>
    <% else %>
      <h1 class="text-center fs-2 pt-4">Update activity</h1>
    <% end %>
      <div class="col-12 px-3">
        <%= simple_form_for [trip, @activity] do |f| %>
          <%= f.input :title %>
          <%= f.input :categories, collection: %w[🍺Bar 🚴🏼‍♀️Sport 🎟️Show 🧘🏼‍♂️Health 🥳Nightlife 🍽️Restaurant 🍵CoffeeShop 🎨Cultural 🏔️Nature ] %>
          <%= f.input :description %>
          <%= f.input :address,
          input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
          wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_URL"]}} %>
          <%= f.input :min_amigos, input_html: { min: 1, max: 10, step: 1, value: 1 } %>
          <%= f.input :max_amigos, input_html: { min: 1, max: 10, step: 1 } %>
          <%= f.input :date, as: :string, required: false, html5: true, as: :date %>
          <%= f.input :photo, as: :file %>
          <div class="mt-5 mb-5 d-flex justify-content-center">
            <%= f.submit class:"btn btn-blue-full" %>
        <% end %>
            <%= link_to 'Back', trip_activities_path, class:" ms-2 btn btn-white text-center" %>
          </div>
      </div>
    </div>
  </div>

app/views/activities/_info_window.html.erb
<h6 class="m-0"><%= activity.title %></h6>
<p class="m-0"><%= activity.address %></p>

app/views/activities/edit.html.erb
<div class="container responsive min-h-100 mb-5 px-3 p-large">
  <div class="row justify-content-center">
    <%= render "form", trip: @trip, activity: @activity %>
  </div>
</div>

app/views/activities/index.html.erb
<div class="container responsive min-h-100 p-large">
  <div class="px-1">
    <div class="nav nav-tabs tabs-activity mx-2 my-3 rounded-4 p-0 row justify-content-between" id="myTab" role="tablist">
      <div class="col-4 nav-item" role="presentation">
        <button class="nav-link active" id="all-activities-tab" data-bs-toggle="tab" data-bs-target="#all-activities-tab-pane" type="button" role="tab" aria-controls="all-activities-tab-pane" aria-selected="true"><i class="fa-solid fa-list"></i></button>
      </div>

      <div class="col-4 nav-item" role="presentation">
        <button class="nav-link" id="create-tab" data-bs-toggle="tab" data-bs-target="#create-tab-pane" type="button" role="tab" aria-controls="create-tab-pane" aria-selected="false"><i class="fa-solid fa-pen-to-square"></i></button>
      </div>

      <div class="col-4 nav-item" role="presentation">
        <button class="nav-link" id="map-tab" data-bs-toggle="tab" data-bs-target="#map-tab-pane" type="button" role="tab" aria-controls="map-tab-pane" aria-selected="false"><i class="fa-solid fa-map-location-dot"></i></button>
      </div>
    </div>

    <div class="tab-content" id="myTabContent">

      <div class="tab-pane fade show active" id="all-activities-tab-pane" role="tabpanel" aria-labelledby="all-activities-tab" tabindex="0">
        <h1 class="text-center fs-2 mt-2 py-2">All activities</h1>
        <% @activities.each do |activity| %>
          <div class="card mb-4 mx-2 rounded-4" style="max-width: 100%;">
            <div class="row g-0">
              <div class="col-5 p-2">
                <% if activity.photo.key != nil %>
                  <%= cl_image_tag activity.photo.key, class:"img-fluid obj-fit activity-img" %>
                <% else %>
                  <%= image_tag "https://source.unsplash.com/random",  class:"img-fluid rounded-start" %>
                <% end %>
              </div>
              <div class="col-7 position-relative">
                <div class="card-body ps-2 pb-0">
                  <h6 class="card-title p-0 m-0 fw-bold fs-6"><%= link_to activity.title, trip_activity_path(@trip, activity), class:"text-decoration-none" %></h6>
                  <p class="p-0 m-0 fw-normal fs-6"><%= activity.categories %></p>
                  <p class="card-text p-0 m-0">🧑🏻‍🤝‍🧑🏽
                    <% if activity.participations.count >= activity.min_amigos %>
                      <span class="text-success"><%= activity.participations.count %></span>/<%= activity.min_amigos %> <%= pluralize_without_count(activity.participations.count, 'amigo') %>
                    <% else %>
                      <span class="text-danger"><%= activity.participations.count %></span>/<%= activity.min_amigos %>
                      <%= pluralize_without_count(activity.participations.count, 'amigo') %>
                    <% end %>
                    <%= link_to trip_activity_path(@trip, activity), class:"btn btn-eye rounded-5 shadow position-absolute" do %>
                      <i class="fa-solid fa-eye text-blue"></i>
                    <% end %>
                  </p>
                <div class="row justify-content-center activity-card-avatars ps-2 pe-1">
                  <div class="col p-0">
                    <ul class="text-start">
                      <% activity.participations.each do |p| %>
                        <li><%= cl_image_tag p.user.photo.key, class:"avatar-xs" %></li>
                      <% end %>
                    </ul>
                  </div>
                </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>

      <div class="tab-pane fade" id="create-tab-pane" role="tabpanel" aria-labelledby="create-tab" tabindex="0">
        <%= render 'form', trip: @trip %>
      </div>

      <div class="tab-pane fade px-3" id="map-tab-pane" role="tabpanel" aria-labelledby="map-tab" tabindex="0">
        <div style="width: 100%; height: 500px;" data-controller="map" data-map-markers-value="<%= @markers.to_json %>" data-map-api-key-value="<%= ENV['MAPBOX_URL'] %>" id="map"></div>
      </div>
    </div>
  </div>
</div>

app/views/activities/map.html.erb
<div data-controller="map" data-map-markers-value="<%= @markers.to_json %>" data-map-api-key-value="<%= ENV['MAPBOX_URL'] %>" id="map"></div>

app/views/activities/new.html.erb
<div class="container responsive min-h-100 p-large">
    <%= render "form", trip: @trip, activity: @activity %>
</div>

app/views/activities/show.html.erb
<div class="container responsive px-3 mb-5 min-h-100 p-large">
  <div class="bg-white rounded-3 mt-3 p-3">
  
  <h1 class="py-2 text-blue text-shadow-none"><%= @activity.title %></h1>
    <div class="row activity-show-card">
      <div class="col-4 col-md-6">
        <%= cl_image_tag @activity.photo.key, class:"activity-show-card--img rounded-3" %>
      </div>
      <div class="col-8 col-md-6 p-0">
        <div class="ps-1">
          <h3 class="fs-5 fw-bold m-0"><%= @activity.categories %></h3>
          <p class="mb-1">Proposed by <%= @activity.creator.first_name %></p>
          <p class="card-text d-inline-block fw-bold m-0 rounded-4 border-blue bg-transparent px-2 py-1 me-1  fs-7"><i class="fa-solid fa-calendar"></i> <%= @activity.date.strftime('%d/%m') %></p>
          <p class="card-text d-inline-block fw-bold m-0 rounded-4 border-blue bg-transparent px-2 py-1 fs-7"><i class="fa-solid fa-users"></i>
          <% if @activity.participations.count >= @activity.min_amigos %>
            <span class="text-success">
            <%= @activity.participations.count %>
            </span>/<%= @activity.min_amigos %>
          <% else %>
            <span class="text-danger">
            <%= @activity.participations.count %></span>
            /<%= @activity.min_amigos %>
          <% end %>
          </p>
        </div>
      </div>
    </div>

    <div class="row justify-content-center activity-show-avatars my-3">
      <h5><strong>Amigos participants</strong></h5>
      <div class="col">
        <ul class="text-start">
          <% @activity.participations.each do |participation| %>
            <li><%= cl_image_tag participation.user.photo.key, class:"avatar-md" %></li>
          <% end %>
        </ul>
      </div>
    </div>
      
    <div class="row">
      <h5><strong>Description</strong></h5>
      <div class="col-12">
        <p class="text-wrap text-break fs-7"><%= @activity.description %></p>
      </div>
    </div>

    <div class="row">
      <div class="col d-flex mt-2 mb-4">
        <% if  @activity.creator?(current_user) %>
          <%= link_to "Edit", edit_trip_activity_path(@activity.trip_id, @activity), class:"btn btn-blue-full me-1" %>
          <%= link_to "Delete", trip_activity_path(@activity.trip_id, @activity), data: { turbo_method: :delete, turbo_confirm: 'Are you sure ?'}, class:"btn btn-danger me-1" %>
        <% elsif @activity.participates?(current_user) %>
          <%= button_to "Quit activity", trip_activity_participation_path(user: current_user, activity_id: @activity.id, participation: @activity.participations.find_by_user_id(current_user.id)), method: :delete, class:"btn btn-danger me-1"  %>
        <% else %>
          <%= button_to "Participate", trip_activity_participations_path(current_user, @activity), method: :post, class:"btn btn-success text-light me-1"  %>
        <% end %>

        <%= link_to "Back", trip_activities_path(@activity.trip), class:"btn btn-blue-white"  %>
      </div>
    </div>

    <div class="row mb-2">
      <div class="col-12">
        <div style="width: 100%; height: 300px;"
            data-controller="map"
            data-map-markers-value="<%= @markers.to_json %>"
            data-map-api-key-value="<%= ENV['MAPBOX_URL'] %>">
        </div>
      </div>
    </div>
  </div>
</div>